[package]
name = "tmkms-nitro-enclave"
version = "0.1.0"
authors = [ "Tomas Tauber <2410580+tomtau@users.noreply.github.com>" ]
edition = "2018"

[dependencies]
anomaly = "0.2"
aws-ne-sys = "0.3"
ed25519-dalek = "1"
nix = "0.17"
serde_json = "1"
subtle = "2"
tendermint = { version = "0.17" }
tendermint-p2p = { version = "0.17" }
tmkms-light = { path = "../../.." }
tmkms-nitro-helper = { path = "../nitro-helper", default-features = false }
tracing = "0.1"
tracing-subscriber = "0.2"
vsock = "0.2"
zeroize = "1"
