[package]
name = "tmkms-nitro-helper"
version = "0.1.0"
authors = [ "Tomas Tauber <2410580+tomtau@users.noreply.github.com>" ]
edition = "2018"

[features]
default = ["main"]
main = ["mz_rusoto_credential", "mz_rusoto_kms", "mz_rusoto_core", "sysinfo"]

[dependencies]
anomaly = "0.2"
bincode = "1"
bytes = "= 0.5"
ed25519 = { version = "1", features = [ "serde" ] }
ed25519-dalek = "1"
mz_rusoto_credential = { version = "0.46", optional = true }
mz_rusoto_kms = { version = "0.46", optional = true }
mz_rusoto_core = { version = "0.46", optional = true }
nix = "0.17"
rand_core = { version = "0.5", features = [ "std" ] }
secrecy = { version = "0.7", features = [ "serde" ] }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
structopt = "0.3"
subtle-encoding = { version = "0.5", features = [ "bech32-preview" ] }
sysinfo = { version = "0.15", optional = true }
tempfile = "3"
tendermint = { version = "0.17" }
thiserror = "1"
tmkms-light = { path = "../../.." }
tokio = { version = "= 0.2", features = [ "rt-core", "time" ] }
toml = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
vsock = "0.2"
zeroize = "1"
